# Generated by Django 3.0.3 on 2020-11-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='d',
        ),
    ]
