# Generated by Django 3.0.3 on 2020-11-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0002_remove_product_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uuiid',
            new_name='uuid',
        ),
    ]
