# Generated by Django 3.0.3 on 2020-11-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0003_auto_20201129_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
    ]
