# Generated by Django 3.0.3 on 2020-11-30 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0004_remove_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 15, 6, 11, 120932)),
        ),
    ]
