# Generated by Django 3.0.3 on 2020-11-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0006_auto_20201130_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
    ]
