# Generated by Django 3.0.3 on 2020-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corn', '0010_delete_myuuidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
